name: 💡 Feature request
description: Förslag eller ny funktionalitet
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Beskrivning
      description: Vad ska byggas? Vilket problem löser det?
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptanskriterier
      description: Hur vet vi att funktionen är klar?
  - type: input
    id: sprint
    attributes:
      label: Sprint
      description: Vilken sprint ska detta ingå i?
